# site settings
title: Forty
subtitle: by HTML5 UP
email: yuanzhao@u.northwestern.edu
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
#baseurl: "/test" # the subpath of your site, e.g. /blog
#url: "https://y-z-zhang.github.io" # the base hostname & protocol for your site
author: Yuanzhao Zhang
street_address: 2145 Sheridan Rd.
city: Evanston
state: IL
zip_code: 60208
country: United States of America
phone: (224) 803-8563

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
