# site settings
title: Yuanzhao Zhang
subtitle: Network Dynamics & Complex Systems
email: yuanzhao@u.northwestern.edu
description: Research Homepage of Yuanzhao Zhang
bio: Ph.D. Candidate, Department of Physics and Astronomy, Northwestern University <br /> <a href="https://scholar.google.com/citations?user=xueImSMAAAAJ&hl=en">Google Scholar</a>, <a href="https://www.researchgate.net/profile/Yuanzhao_Zhang">Research Gate</a>, <a href="assets/cv.pdf">Curriculum Vitae</a>
#baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://y-zhang.com" #"https://y-z-zhang.github.io" # the base hostname & protocol for your site
author: Yuanzhao Zhang
street_address: 2145 Sheridan Rd.
city: Evanston
state: IL
zip_code: 60208
country: United States of America
phone: (224) 803-8563

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 11

# social settings
500px_url:
facebook_url:
github_url: https://github.com/y-z-zhang
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zhangyuanzhao45

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
